### ISSUE TITLE
ui of upscale button was not correct

### ISSUE THREAD

**Issue by AndyLeAI** [Haoming02/sd-webui-moar-generate#4]
i fount the UI of Upscale button was not correct, text "Upscale" too big compare to bouding box. and when i set it in "uder result" it was disappeard !
<img width="64" alt="image" src="https://github.com/user-attachments/assets/8c2e4259-9f5d-4697-ad95-a17b2f0b8c21">

**Comment by Haoming02** [comment]
What version of Webui are you using?

And are you using any theme/style extensions?

Cause it works fine on my end:

<p align="center"><img src="https://github.com/user-attachments/assets/b7a0c304-82d4-4f1d-84f4-af7cb42aa9ea"></p>
